// Generated by CoffeeScript 1.3.3
(function() {
  var app, express, io, path, server;

  path = require("path");

  express = require("express");

  app = express();

  app.configure(function() {
    app.set("port", process.env.PORT || 3000);
    app.set("view", "views");
    app.set("view engine", "jade");
    app.use(express.favicon());
    app.use(express.logger("dev"));
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(app.router);
    return app.use(express["static"]("public"));
  });

  app.configure("development", function() {
    return app.use(express.errorHandler());
  });

  app.configure("production", function() {
    return app.set("port", 80);
  });

  server = require("http").createServer(app).listen(app.get("port"), function() {
    return console.log("Express server listening on port " + (app.get('port')) + ".");
  });

  io = require("socket.io").listen(server);

  require("./lib/main")(app, io);

}).call(this);
